/**
 * Canonical in-person lesson lifecycle status constants and transition helpers for Tutors.
 */

export const LESSON_STATUS = {
  PENDING: 'pending',
  MATCHING: 'matching',
  OFFERED: 'offered',
  ACCEPTED: 'accepted',
  TRAVELLING: 'travelling',
  ARRIVED: 'arrived',
  WAITING_STUDENT: 'waiting_student',
  PREPARING_FOR_LESSON: 'preparing_for_lesson',
  IN_SESSION: 'in_session',
  IN_PROGRESS: 'in_progress',
  ENDING_REQUESTED: 'ending_requested',
  COMPLETED: 'completed',
  SETTLED: 'settled',
  CANCELED: 'canceled',
  CANCELED_DURING: 'canceled_during',
  CANCELED_BY_STUDENT: 'canceled_by_student',
  CANCELED_BY_TUTOR: 'canceled_by_tutor',
  EXPIRED: 'expired',
};

export const TERMINAL_STATUSES = [
  LESSON_STATUS.COMPLETED,
  LESSON_STATUS.SETTLED,
  LESSON_STATUS.CANCELED,
  LESSON_STATUS.CANCELED_DURING,
  LESSON_STATUS.CANCELED_BY_STUDENT,
  LESSON_STATUS.CANCELED_BY_TUTOR,
  LESSON_STATUS.EXPIRED,
];

export const ACTIVE_LESSON_STATUSES = [
  LESSON_STATUS.IN_SESSION,
  LESSON_STATUS.IN_PROGRESS,
  LESSON_STATUS.ENDING_REQUESTED,
];

export const TRAVEL_LIFECYCLE_STATUSES = [
  LESSON_STATUS.ACCEPTED,
  LESSON_STATUS.TRAVELLING,
  LESSON_STATUS.ARRIVED,
  LESSON_STATUS.WAITING_STUDENT,
  LESSON_STATUS.PREPARING_FOR_LESSON,
];

export const ACTIVE_TRACKING_STATUSES = [
  LESSON_STATUS.ACCEPTED,
  LESSON_STATUS.TRAVELLING,
  LESSON_STATUS.ARRIVED,
  LESSON_STATUS.WAITING_STUDENT,
  LESSON_STATUS.PREPARING_FOR_LESSON,
];

export const CANCELLATION_STATUSES = [
  LESSON_STATUS.CANCELED,
  LESSON_STATUS.CANCELED_DURING,
  LESSON_STATUS.CANCELED_BY_STUDENT,
  LESSON_STATUS.CANCELED_BY_TUTOR,
];

// Valid state machine transitions
export const ALLOWED_TRANSITIONS = {
  [LESSON_STATUS.PENDING]: [
    LESSON_STATUS.MATCHING,
    LESSON_STATUS.OFFERED,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.EXPIRED,
  ],
  [LESSON_STATUS.MATCHING]: [
    LESSON_STATUS.OFFERED,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.EXPIRED,
  ],
  [LESSON_STATUS.OFFERED]: [
    LESSON_STATUS.ACCEPTED,
    LESSON_STATUS.MATCHING,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
    LESSON_STATUS.EXPIRED,
  ],
  [LESSON_STATUS.ACCEPTED]: [
    LESSON_STATUS.TRAVELLING,
    LESSON_STATUS.ARRIVED,
    LESSON_STATUS.WAITING_STUDENT,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.TRAVELLING]: [
    LESSON_STATUS.ARRIVED,
    LESSON_STATUS.WAITING_STUDENT,
    LESSON_STATUS.PREPARING_FOR_LESSON,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.ARRIVED]: [
    LESSON_STATUS.WAITING_STUDENT,
    LESSON_STATUS.PREPARING_FOR_LESSON,
    LESSON_STATUS.IN_SESSION,
    LESSON_STATUS.IN_PROGRESS,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.WAITING_STUDENT]: [
    LESSON_STATUS.PREPARING_FOR_LESSON,
    LESSON_STATUS.IN_SESSION,
    LESSON_STATUS.IN_PROGRESS,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.PREPARING_FOR_LESSON]: [
    LESSON_STATUS.IN_SESSION,
    LESSON_STATUS.IN_PROGRESS,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.IN_SESSION]: [
    LESSON_STATUS.ENDING_REQUESTED,
    LESSON_STATUS.COMPLETED,
    LESSON_STATUS.SETTLED,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_DURING,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.IN_PROGRESS]: [
    LESSON_STATUS.ENDING_REQUESTED,
    LESSON_STATUS.COMPLETED,
    LESSON_STATUS.SETTLED,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_DURING,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.ENDING_REQUESTED]: [
    LESSON_STATUS.COMPLETED,
    LESSON_STATUS.SETTLED,
    LESSON_STATUS.IN_SESSION,
    LESSON_STATUS.IN_PROGRESS,
    LESSON_STATUS.CANCELED,
    LESSON_STATUS.CANCELED_DURING,
    LESSON_STATUS.CANCELED_BY_STUDENT,
    LESSON_STATUS.CANCELED_BY_TUTOR,
  ],
  [LESSON_STATUS.COMPLETED]: [
    LESSON_STATUS.SETTLED,
  ],
  [LESSON_STATUS.SETTLED]: [],
  [LESSON_STATUS.CANCELED]: [],
  [LESSON_STATUS.CANCELED_DURING]: [],
  [LESSON_STATUS.CANCELED_BY_STUDENT]: [],
  [LESSON_STATUS.CANCELED_BY_TUTOR]: [],
  [LESSON_STATUS.EXPIRED]: [],
};

export function canTransition(currentStatus, targetStatus) {
  if (!currentStatus || !targetStatus) return false;
  const current = String(currentStatus).toLowerCase();
  const target = String(targetStatus).toLowerCase();
  if (current === target) return true;
  const allowed = ALLOWED_TRANSITIONS[current];
  return Array.isArray(allowed) && allowed.includes(target);
}

export function isTerminalStatus(status) {
  if (!status) return false;
  return TERMINAL_STATUSES.includes(String(status).toLowerCase());
}

export function isActiveLessonStatus(status) {
  if (!status) return false;
  return ACTIVE_LESSON_STATUSES.includes(String(status).toLowerCase());
}

export function isTravelLifecycleStatus(status) {
  if (!status) return false;
  return TRAVEL_LIFECYCLE_STATUSES.includes(String(status).toLowerCase());
}

export function isActiveTrackingStatus(status) {
  if (!status) return false;
  return ACTIVE_TRACKING_STATUSES.includes(String(status).toLowerCase());
}

export function isCancellationStatus(status) {
  if (!status) return false;
  return CANCELLATION_STATUSES.includes(String(status).toLowerCase());
}

export default {
  LESSON_STATUS,
  TERMINAL_STATUSES,
  ACTIVE_LESSON_STATUSES,
  TRAVEL_LIFECYCLE_STATUSES,
  ACTIVE_TRACKING_STATUSES,
  CANCELLATION_STATUSES,
  ALLOWED_TRANSITIONS,
  canTransition,
  isTerminalStatus,
  isActiveLessonStatus,
  isTravelLifecycleStatus,
  isActiveTrackingStatus,
  isCancellationStatus,
};
